
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN P5 [get_ports clk]
set_property PACKAGE_PIN P4 [get_ports reset]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
#set IM_DATA_FILENAME "F:\Grade3_1\cpu\cpu\project\cpupro\cpupro.ip_user_files\mem_init_files\im_data.mem"

set_property PACKAGE_PIN F6 [get_ports {op[7]}]
set_property PACKAGE_PIN G4 [get_ports {op[6]}]
set_property PACKAGE_PIN G3 [get_ports {op[5]}]
set_property PACKAGE_PIN J4 [get_ports {op[4]}]
set_property PACKAGE_PIN H4 [get_ports {op[3]}]
set_property PACKAGE_PIN J3 [get_ports {op[2]}]
set_property PACKAGE_PIN J2 [get_ports {op[1]}]
set_property PACKAGE_PIN K2 [get_ports {op[0]}]
set_property PACKAGE_PIN K1 [get_ports {pc[7]}]
set_property PACKAGE_PIN H6 [get_ports {pc[6]}]
set_property PACKAGE_PIN H5 [get_ports {pc[5]}]
set_property PACKAGE_PIN J5 [get_ports {pc[4]}]
set_property PACKAGE_PIN K6 [get_ports {pc[3]}]
set_property PACKAGE_PIN L1 [get_ports {pc[2]}]
set_property PACKAGE_PIN M1 [get_ports {pc[1]}]
set_property PACKAGE_PIN K3 [get_ports {pc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[0]}]

///////////////////////////////8个数码管位选信号/////////////////////////////////
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {an[3]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {an[2]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {an[1]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {an[0]}]

set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {an1[3]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {an1[2]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {an1[1]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {an1[0]}]

///////////////////////////////////数码管段选信号//////////////////////////////////
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {seg[0]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {seg[1]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {seg[2]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {seg[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {seg[4]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {seg[5]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {seg[6]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {seg[7]}]

set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {seg1[0]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {seg1[1]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {seg1[2]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {seg1[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {seg1[4]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {seg1[5]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {seg1[6]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {seg1[7]}]
