
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN P5 [get_ports clk]
set_property PACKAGE_PIN P4 [get_ports reset]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property PACKAGE_PIN F6 [get_ports {op[7]}]
set_property PACKAGE_PIN G4 [get_ports {op[6]}]
set_property PACKAGE_PIN G3 [get_ports {op[5]}]
set_property PACKAGE_PIN J4 [get_ports {op[4]}]
set_property PACKAGE_PIN H4 [get_ports {op[3]}]
set_property PACKAGE_PIN J3 [get_ports {op[2]}]
set_property PACKAGE_PIN J2 [get_ports {op[1]}]
set_property PACKAGE_PIN K2 [get_ports {op[0]}]
set_property PACKAGE_PIN K1 [get_ports {pc[7]}]
set_property PACKAGE_PIN H6 [get_ports {pc[6]}]
set_property PACKAGE_PIN H5 [get_ports {pc[5]}]
set_property PACKAGE_PIN J5 [get_ports {pc[4]}]
set_property PACKAGE_PIN K6 [get_ports {pc[3]}]
set_property PACKAGE_PIN L1 [get_ports {pc[2]}]
set_property PACKAGE_PIN M1 [get_ports {pc[1]}]
set_property PACKAGE_PIN K3 [get_ports {pc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pc[0]}]


